import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:restaurant_app/core/constants/app_constants.dart';
import 'package:restaurant_app/core/di/injection_container.dart';
import 'package:restaurant_app/features/auth/presentation/bloc/auth_bloc.dart';
import 'package:restaurant_app/features/auth/presentation/pages/login_page.dart';
import 'package:restaurant_app/features/cart/presentation/bloc/cart_bloc.dart';
import 'package:restaurant_app/features/menu/presentation/pages/menu_page.dart';
import 'package:restaurant_app/features/orders/presentation/pages/admin_dashboard_page.dart';
import 'package:restaurant_app/features/orders/presentation/pages/rider_dashboard_page.dart';

// Generated by `flutterfire configure` — not included here since it's
// project-specific. Run that command against your own Firebase project
// and it will create this file.
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await Hive.initFlutter();

  // Stripe sandbox publishable key — safe to ship in the client.
  // Replace with your own from the Stripe dashboard (test mode).
  Stripe.publishableKey = 'pk_test_REPLACE_WITH_YOUR_PUBLISHABLE_KEY';

  await initDependencies();

  runApp(const RestaurantApp());
}

class RestaurantApp extends StatelessWidget {
  const RestaurantApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider(create: (_) => sl<AuthBloc>()..add(const AppStarted())),
        // App-wide cart so it survives navigation between menu/cart/checkout.
        BlocProvider(create: (_) => sl<CartBloc>()..add(const LoadCartEvent())),
      ],
      child: MaterialApp(
        title: 'FoodieGo',
        debugShowCheckedModeBanner: false,
        themeMode: ThemeMode.dark,
        darkTheme: ThemeData.dark().copyWith(
          scaffoldBackgroundColor: const Color(0xFF1A1614),
          colorScheme: const ColorScheme.dark(
            primary: Color(0xFFD35400),
            secondary: Color(0xFFE67E22),
            surface: Color(0xFF241E1C),
            onSurface: Color(0xFFFDF5E6),
            onPrimary: Color(0xFFFDF5E6),
          ),
          appBarTheme: const AppBarTheme(
            backgroundColor: Color(0xFF1A1614),
            elevation: 0,
            foregroundColor: Color(0xFFFDF5E6),
          ),
          cardTheme: CardThemeData(
            color: const Color(0xFF241E1C),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
          ),
        ),
        theme: ThemeData.dark().copyWith(
          scaffoldBackgroundColor: const Color(0xFF1A1614),
          colorScheme: const ColorScheme.dark(
            primary: Color(0xFFD35400),
            secondary: Color(0xFFE67E22),
            surface: Color(0xFF241E1C),
            onSurface: Color(0xFFFDF5E6),
            onPrimary: Color(0xFFFDF5E6),
          ),
          appBarTheme: const AppBarTheme(
            backgroundColor: Color(0xFF1A1614),
            elevation: 0,
            foregroundColor: Color(0xFFFDF5E6),
          ),
          cardTheme: CardThemeData(
            color: const Color(0xFF241E1C),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
          ),
        ),
        home: const _RootGate(),
      ),
    );
  }
}

/// Decides the first screen based on auth state without duplicating the
/// role-switch logic that also lives in AppRouter.goToRoleHome — this is
/// the one exception (cold start, before a Navigator exists to push into).
class _RootGate extends StatelessWidget {
  const _RootGate();

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<AuthBloc, AuthState>(
      builder: (context, state) {
        if (state is AuthLoading || state is AuthInitial) {
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }
        if (state is AuthAuthenticated) {
          return switch (state.user.role) {
            AppConstants.roleAdmin => const AdminDashboardPage(),
            AppConstants.roleRider => const RiderDashboardPage(),
            _ => const MenuPage(),
          };
        }
        return const LoginPage();
      },
    );
  }
}
